mytube/apps/feed/urls.py
from django.urls import path

from . import views
app_name = 'feed'

urlpatterns = [
    path('', views.MainFeedView.as_view(), name='index'),
    path('history', views.HistoryListView.as_view(), name='history'),
    path('liked', views.LikedVideosListView.as_view(), name='liked'),
    path('most-viewed', views.MostViewedListView.as_view(), name='most-viewed'),
    path('top', views.TopRatedListView.as_view(), name='top'),
]

mytube/apps/video/urls.py
from django.urls import path

from . import views
app_name = 'video'

urlpatterns = [
    path('<pk>', views.VideoDetailView.as_view(), name='watch'),
    path('<pk>/add_comment', views.AddCommentView.as_view(), name='add_comment'),
    path('<pk>/rate', views.rate_video, name='rate_video'),
    path('new', views.AddVideoView.as_view(), name='add'),
]

mytube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mytube.apps.feed.urls', namespace='feed')),
    path('u/', include('mytube.apps.channel.urls', namespace='channel')),
    path('v/', include('mytube.apps.video.urls', namespace='video')),
    path('p/', include('mytube.apps.playlist.urls', namespace='playlist')),
    path('account/', include('mytube.apps.account.urls', namespace='account')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytube/apps/feed/models.py
from django.db import models

# Create your models here.

mytube/apps/feed/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, FloatField, Case, When

from mytube.apps.video.models import Video, History, VideoRating


class MainFeedView(ListView):
    '''
    List the most recent public videos
    '''

    model = Video
    template_name = 'feed/index.html'
    context_object_name = 'videos'

    def get_queryset(self):
        '''
        Custom queryset to fetch only public videos
        '''

        return self.model.objects.filter(visibility='PUBLIC').order_by('-created')


class VideoListView(ListView):
    template_name = 'feed/list.html'
    context_object_name = 'entries'
    list_title = ''

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['list_title'] = self.list_title
        return context


class AuthRequiredVideoListView(LoginRequiredMixin, VideoListView):
    login_url = reverse_lazy('account:login')

    def get_queryset(self):
        objects = self.model.objects.filter(user=self.request.user)
        result = [x.video for x in objects]
        return result


class HistoryListView(AuthRequiredVideoListView):
    '''
    List the user's history
    '''
    list_title = 'History'
    model = History


class LikedVideosListView(AuthRequiredVideoListView):
    '''
    List the user's liked videos
    '''
    list_title = 'Liked Videos'
    model = VideoRating


class MostViewedListView(VideoListView):
    '''
    List the most viewed videos
    '''
    list_title = 'Most Viewed'
    model = Video

    def get_queryset(self):
        return self.model.objects.all().order_by('-views')


class TopRatedListView(VideoListView):
    '''
    List the user's liked videos
    '''
    list_title = 'Top Rated'
    model = Video

    def get_queryset(self):
        return Video.objects.all().annotate(
            count=Sum(
                Case(
                    When(video_rating__rating='LIKE', then=1),
                    When(video_rating__rating='DISLIKE', then=-0.33),
                    default=0,
                ), output_field=FloatField()
            )
        ).order_by('-count')

mytube/apps/feed/templates/feed/history.html
{% extends 'base.html' %}
{% load humanize %}
{% load video_extras %}
{% block title %}History{% endblock %}

{% block content %}
<div class="container is-fluid">
    <div class="subtitle">Watch History</div>
    <div class="columns is-multiline">
    {% for entry in entries %}
    {% with video=entry.video %}
            <div class="column is-3">
                <div class="video-list-thumb">
                    <a href="{% url 'video:watch' video.id %}">

                        {% if video.preview_thumb %}
                        <img src="{{ video.preview_thumb.url }}" />
                        {% else %}
                        <img src="https://via.placeholder.com/320x180" />
                        {% endif %}
                    </a>

                    <div class="video-thumb-duration">
                        {% get_duration video.duration %}
                    </div>
                </div>
            </div>
            <div class="column is-3">
                <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                    <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                </a>
                <a href="{% url 'channel:index' video.user.username %}" class="is-size-7 has-text-link">
                    {{video.user.username }}</a>
                    <div class="is-size-7 has-text-grey">
                        {{ video.views }} views
                    </div>
                    <div class="is-size-7">
                        {{ video.description |truncatechars:100}}
                    </div>
            </div>
            {% endwith %}
            {% endfor %}
        </div>
</div>

{% endblock %}

mytube/apps/feed/templates/feed/index.html
{% extends 'base.html' %}
{% load humanize %}
{% load video_extras %}
{% block content %}
<div class="container is-fluid">
    <div class="subtitle">Recently Uploaded</div>
    <div class="columns is-multiline">
        {% for video in videos %}
        <div class="column is-3">
            <div class="video-list-thumb">
                <a href="{% url 'video:watch' video.id %}">

                    {% if video.preview_thumb %}
                    <img src="{{ video.preview_thumb.url }}" />
                    {% else %}
                    <img src="https://via.placeholder.com/320x180" />
                    {% endif %}
                </a>

                <div class="video-thumb-duration">
                    {% get_duration video.duration %}
                </div>
            </div>
            <div>
                <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                    <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                </a>
                <a href="{% url 'channel:index' video.user.username %}" class="is-size-7">
                    {{video.user.username }}</a>
                <div class="is-size-7 has-text-grey level">
                    <span class="level-left">
                        <span class="level-item">
                            {{ video.created|naturaltime }}
                        </span>
                    </span>
                    <span class="level-right">
                        <span class="level-item">
                            {{ video.views }} views
                        </span>
                    </span>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

mytube/apps/feed/templates/feed/list.html
{% extends 'base.html' %}
{% load humanize %}
{% load video_extras %}
{% block title %}{{ list_title }}{% endblock %}

{% block content %}
<div class="container is-fluid">
    <div class="subtitle">{{ list_title }}</div>
    <div class="columns is-multiline">
    {% for video in entries %}

            <div class="column is-3">
                <div class="video-list-thumb">
                    <a href="{% url 'video:watch' video.id %}">

                        {% if video.preview_thumb %}
                        <img src="{{ video.preview_thumb.url }}" />
                        {% else %}
                        <img src="https://via.placeholder.com/320x180" />
                        {% endif %}
                    </a>

                    <div class="video-thumb-duration">
                        {% get_duration video.duration %}
                    </div>
                </div>
            </div>
            <div class="column is-3">
                <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                    <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                </a>
                <a href="{% url 'channel:index' video.user.username %}" class="is-size-7 has-text-link">
                    {{video.user.username }}</a>
                    <div class="is-size-7 has-text-grey">
                        {{ video.views }} views
                    </div>
                    <div class="is-size-7">
                        {{ video.description |truncatechars:100}}
                    </div>
            </div>

            {% endfor %}
        </div>
</div>

{% endblock %}