mytube/apps/channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<str:username>', views.UserVideoListView.as_view(), name='index'),
    path('<str:username>/playlists',
         views.PlaylistListView.as_view(), name='playlists')
]

mytube/apps/playlist/urls.py
from django.urls import path

from . import views
app_name = 'playlist'

urlpatterns = [
    path('add', views.add_to_playlist, name='add'),
    path('watch-later', views.WatchLaterListView.as_view(), name='watch_later'),
    path('favourites', views.FavouritesListView.as_view(), name='favourites'),
    path('<pk>', views.PlaylistDetailView.as_view(), name='detail'),
]

mytube/apps/video/urls.py
from django.urls import path

from . import views
app_name = 'video'

urlpatterns = [
    path('<pk>', views.VideoDetailView.as_view(), name='watch'),
    path('<pk>/add_comment', views.AddCommentView.as_view(), name='add_comment'),
    path('<pk>/rate', views.rate_video, name='rate_video'),
    path('new', views.AddVideoView.as_view(), name='add'),
]

mytube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mytube.apps.feed.urls', namespace='feed')),
    path('u/', include('mytube.apps.channel.urls', namespace='channel')),
    path('v/', include('mytube.apps.video.urls', namespace='video')),
    path('p/', include('mytube.apps.playlist.urls', namespace='playlist')),
    path('account/', include('mytube.apps.account.urls', namespace='account')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytube/apps/playlist/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

from mytube.apps.video.models import Video

class Playlist(models.Model):
    VISIBILITY = (
        ('PUBLIC', 'Public'),
        ('PRIVATE', 'Private'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, default='Untitled Playlist')
    visibility = models.CharField(
        max_length=7, default='PUBLIC', choices=VISIBILITY)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # False for system created playlists like favorites and watch later
    deletable = models.BooleanField(default=True)

    class Meta:
        ordering = ['deletable']

    def __str__(self):
        return '[{}] {} <{}>'.format(self.visibility, self.name, self.user)

    def add_video(self, video: Video) -> None:
        try:
            # Check if already exists
            PlaylistVideoMapping.objects.get(playlist=self, video=video)
        except:
            PlaylistVideoMapping(playlist=self, video=video).save()

    def remove_video(self, video: Video) -> None:
        try:
            PlaylistVideoMapping.objects.get(
                playlist=self, video=video).delete()
        except:
            return

    def has_video(self, video: Video) -> bool:
        try:
            PlaylistVideoMapping.objects.get(playlist=self, video=video)
            return True
        except:
            return False

    def length(self):
        return PlaylistVideoMapping.objects.filter(playlist=self).count()

    def get_videos(self, n=4):
        video_ids = PlaylistVideoMapping.objects.filter(
            playlist=self).values_list('video', flat=True).distinct()[:n]

        return Video.objects.filter(id__in=video_ids)


class PlaylistVideoMapping(models.Model):
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

mytube/apps/channel/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.contrib.auth.models import User

from mytube.apps.video.models import Video
from mytube.apps.playlist.models import Playlist

class UserVideoListView(ListView):
    '''
    - List the public videos of any user
    - List all the videos of the logged in user
    '''

    model = Video
    template_name = 'channel/index.html'
    context_object_name = 'videos'

    def get_queryset(self):
        '''
        Custom queryset to fetch only public videos
        '''

        username = self.kwargs.get('username')
        if self.request.user.username == username:
            self.user = self.request.user
            return self.model.objects.filter(user=self.request.user).order_by('-created')

        self.user = get_object_or_404(User, username=username)
        return self.model.objects.filter(user=self.user, visibility='PUBLIC').order_by('-created')

    def get_context_data(self, *args, **kwargs):
        context_data = super(
            UserVideoListView, self).get_context_data(*args, **kwargs)
        context_data['channel_user'] = self.user
        return context_data


class PlaylistListView(UserVideoListView):
    model = Playlist
    context_object_name = 'playlists'
    template_name = 'channel/playlist.html'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        self.user = user
        if self.request.user.id == user.id:
            return Playlist.objects.filter(user=self.request.user)

        return Playlist.objects.filter(user=user, visibility='PUBLIC')

mytube/apps/playlist/views.py
from django.shortcuts import get_object_or_404, Http404, HttpResponseRedirect, reverse
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from mytube.apps.video.models import Video
from .models import Playlist, PlaylistVideoMapping

class PlaylistDetailView(ListView):
    '''
    List the videos of a playlist
    '''

    model = PlaylistVideoMapping
    template_name = 'playlist/detail.html'
    context_object_name = 'entries'

    def get_queryset(self):
        '''
        Custom queryset to fetch playlist
        '''

        if self.kwargs.get('pk') is not None:
            self.id = self.kwargs.get('pk')

        self.playlist: Playlist = get_object_or_404(Playlist, id=self.id)

        if self.playlist.visibility == 'PRIVATE' and self.playlist.user != self.request.user:
            raise Http404

        return self.model.objects.filter(playlist=self.playlist)

    def get_context_data(self, *args, **kwargs):
        context_data = super(
            PlaylistDetailView, self).get_context_data(*args, **kwargs)
        context_data['playlist'] = self.playlist

        return context_data


class WatchLaterListView(LoginRequiredMixin, PlaylistDetailView):
    login_url = reverse_lazy('account:login')

    def dispatch(self, *args, **kwargs):
        self.id = Playlist.objects.get(
            deletable=False, name='Watch later', user=self.request.user).id
        return super(WatchLaterListView, self).dispatch(*args, **kwargs)


class FavouritesListView(LoginRequiredMixin, PlaylistDetailView):
    login_url = reverse_lazy('account:login')

    def dispatch(self, *args, **kwargs):
        self.id = Playlist.objects.get(
            deletable=False, name='Favourites', user=self.request.user).id
        return super(FavouritesListView, self).dispatch(*args, **kwargs)


@login_required(login_url=reverse_lazy('account:login'))
def add_to_playlist(request):
    if request.method == 'POST':
        video_pk = request.POST.get('video_pk')
        playlist_pk = request.POST.get('playlist_pk')

        video = get_object_or_404(Video, id=video_pk)

        if playlist_pk is None:
            # Create new playlist
            name = request.POST.get('name', 'Untitled Playlist')
            visibility = request.POST.get('visibility', 'PUBLIC')

            playlist: Playlist = Playlist(
                name=name, user=request.user, visibility=visibility)
            playlist.save()
        else:
            playlist: Playlist = get_object_or_404(
                Playlist, id=playlist_pk, user=request.user)

        if playlist.has_video(video):
            playlist.remove_video(video)
        else:
            playlist.add_video(video)

    return HttpResponseRedirect(reverse('video:watch', args=(video_pk,)))

mytube/apps/channel/templates/channel/index.html
{% extends 'base_no_padding.html' %}
{% load humanize %}
{% load video_extras %}
{% block title %}Videos of {{ channel_user.username }}{% endblock %}
{% block content %}
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column is-narrow">
                    <figure class="image is-128x128" style="margin: auto;">
                        <img class="is-rounded" src="https://via.placeholder.com/128" style="max-height: none;">
                    </figure>
                </div>

                <div class="column">
                    <h1 class="title">
                        {{ channel_user.username }}
                    </h1>
                    <h2 class="subtitle">
                        {{ videos.count }} videos
                    </h2>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="section">
    <div class="vspace"></div>
    <div class="columns is-multiline">
        {% for video in videos %}
        <div class="column is-3">
            <div class="video-list-thumb">
                <a href="{% url 'video:watch' video.id %}">

                    {% if video.preview_thumb %}
                    <img src="{{ video.preview_thumb.url }}" />
                    {% else %}
                    <img src="https://via.placeholder.com/320x180" />
                    {% endif %}
                </a>

                <div class="video-thumb-duration">
                    {% get_duration video.duration %}
                </div>
                {% if video.visibility == "UNLISTED" %}
                <div class="video-thumb-tag video-thumb-tag-unlisted">
                    Unlisted
                </div>
                {% endif %}

                {% if video.visibility == "PRIVATE" %}
                <div class="video-thumb-tag video-thumb-tag-private">
                    Private
                </div>
                {% endif %}
            </div>
            <div>
                <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                    <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                </a>
                <div class="is-size-7 has-text-link">{{ video.user.username }}</div>
                <div class="is-size-7 has-text-grey level">
                    <span class="level-left">
                        <span class="level-item">
                            {{ video.created|naturaltime }}
                        </span>
                    </span>
                    <span class="level-right">
                        <span class="level-item">
                            {{ video.views }} views
                        </span>
                    </span>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

mytube/apps/channel/templates/channel/playlist.html
{% extends 'base_no_padding.html' %}
{% load humanize %}
{% load video_extras %}
{% block title %}Playlists of {{ channel_user.username }}{% endblock %}
{% block content %}
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column is-narrow">
                    <figure class="image is-128x128" style="margin: auto;">
                        <img class="is-rounded" src="https://via.placeholder.com/128" style="max-height: none;">
                    </figure>
                </div>

                <div class="column">
                    <h1 class="title">
                        {{ channel_user.username }}
                    </h1>
                    <h2 class="subtitle">
                        Playlists
                    </h2>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="section">
    {% for playlist in playlists %}
    <div class="mb-large">
        <a href="{% url 'playlist:detail' playlist.id %}" class="subtitle has-text-white">{{ playlist.name }}</a>
        <p class="is-size-7 mb-medium">{{ playlist.length }} videos</p>

        <div class="columns is-multiline">
            {% for video in playlist.get_videos %}
            <div class="column is-3">
                <div class="video-list-thumb">
                    <a href="{% url 'video:watch' video.id %}">

                        {% if video.preview_thumb %}
                        <img src="{{ video.preview_thumb.url }}" />
                        {% else %}
                        <img src="https://via.placeholder.com/320x180" />
                        {% endif %}
                    </a>

                    <div class="video-thumb-duration">
                        {% get_duration video.duration %}
                    </div>
                    {% if video.visibility == "UNLISTED" %}
                    <div class="video-thumb-tag video-thumb-tag-unlisted">
                        Unlisted
                    </div>
                    {% endif %}

                    {% if video.visibility == "PRIVATE" %}
                    <div class="video-thumb-tag video-thumb-tag-private">
                        Private
                    </div>
                    {% endif %}
                </div>
                <div>
                    <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                        <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                    </a>
                    <div class="is-size-7 has-text-link">{{ video.user.username }}</div>
                    <div class="is-size-7 has-text-grey level">
                        <span class="level-left">
                            <span class="level-item">
                                {{ video.created|naturaltime }}
                            </span>
                        </span>
                        <span class="level-right">
                            <span class="level-item">
                                {{ video.views }} views
                            </span>
                        </span>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
        <div class="is-size-7 has-text-right">
            <a href="{% url 'playlist:detail' playlist.id %}" class="is-size-7 has-text-right">View playlist</a>
        </div>
        <hr />
    </div>
    {% endfor %}
</div>

{% endblock %}