mytube/apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.login, name='login'),
    path('create', views.register, name='register'),
    path('logout', views.logout, name='logout'),
]

mytube/apps/channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<str:username>', views.UserVideoListView.as_view(), name='index'),
    path('<str:username>/playlists',
         views.PlaylistListView.as_view(), name='playlists')
]

mytube/apps/video/urls.py
from django.urls import path

from . import views
app_name = 'video'

urlpatterns = [
    path('<pk>', views.VideoDetailView.as_view(), name='watch'),
    path('<pk>/add_comment', views.AddCommentView.as_view(), name='add_comment'),
    path('<pk>/rate', views.rate_video, name='rate_video'),
    path('new', views.AddVideoView.as_view(), name='add'),
]

mytube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mytube.apps.feed.urls', namespace='feed')),
    path('u/', include('mytube.apps.channel.urls', namespace='channel')),
    path('v/', include('mytube.apps.video.urls', namespace='video')),
    path('p/', include('mytube.apps.playlist.urls', namespace='playlist')),
    path('account/', include('mytube.apps.account.urls', namespace='account')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mytube/apps/video/models.py
from hashlib import md5
from time import time
import uuid

from django.db import models
from django.contrib.auth.models import User


def get_bucket() -> str:
    number_str: str = str(int(time()) % 100)
    bucket: str = md5(number_str.encode()).hexdigest()
    return bucket


def video_upload_to(video: models.Model, filename: str) -> str:
    video.original_file_name = filename

    if '.' not in filename:
        ext = 'mp4'
    else:
        ext = filename[filename.rfind('.') + 1:]

    return 'uploads/{}/{}.{}'.format(get_bucket(), str(uuid.uuid4()), ext)


def thumb_upload_to(video: models.Model, filename: str) -> str:
    return 'thumbs/{}/{}.jpg'.format(get_bucket(), video.id)


class Video(models.Model):
    VISIBILITY = (
        ('PUBLIC', 'Public'),
        ('PRIVATE', 'Private'),
        ('UNLISTED', 'Unlisted'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    title = models.CharField(max_length=255, default='Untitled Video')
    description = models.TextField(null=True, blank=True)

    video_file = models.FileField(upload_to=video_upload_to)
    original_file_name = models.CharField(
        max_length=512, default='', blank=True)

    visibility = models.CharField(
        max_length=8, default='PUBLIC', choices=VISIBILITY)

    duration = models.IntegerField(null=True, blank=True)
    views = models.IntegerField(default=0)

    preview_thumb = models.FileField(
        null=True, blank=True, upload_to=thumb_upload_to)

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='videos')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def increment_view_count(self):
        self.views = models.F('views') + 1

    def rate_video(self, user: User, rating: str):
        try:
            # Update rating if already rated
            video_rating = VideoRating.objects.get(video=self, user=user)
            video_rating.rating = rating
            video_rating.save()
        except:
            VideoRating(video=self, user=user, rating=rating).save()

    def like_count(self):
        return VideoRating.objects.filter(video=self, rating='LIKE').count()

    def dislike_count(self):
        return VideoRating.objects.filter(video=self, rating='DISLIKE').count()

    def like_percentage(self):
        like_count = self.like_count()
        try:
            return like_count / (like_count + self.dislike_count()) * 100
        except ArithmeticError:
            return 100

    def user_rating(self, user, get_rating_object=False):
        print(user)
        try:
            rating = VideoRating.objects.get(video=self, user=user)
            if not get_rating_object:
                rating = rating.rating
            print(rating)
            return rating
        except:
            import traceback
            traceback.print_exc()
            return None

    def __str__(self):
        return '<{}> {}'.format(self.id, self.title)


class Comment(models.Model):
    video = models.ForeignKey(
        Video, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    text = models.TextField()

    created = models.DateTimeField(auto_now_add=True)


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(
        Video, on_delete=models.CASCADE)
    watched_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-watched_time']
        verbose_name_plural = 'history entries'

    def __str__(self):
        return '{} - {}'.format(self.user.username, self.video.id)


class VideoRating(models.Model):
    RATING = (('LIKE', 'Like'), ('DISLIKE', 'Dislike'))
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    video = models.ForeignKey(
        Video, on_delete=models.CASCADE, related_name='video_rating')
    rating = models.CharField(max_length=7, choices=RATING, default='LIKE')

mytube/apps/channel/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.contrib.auth.models import User

from mytube.apps.video.models import Video
from mytube.apps.playlist.models import Playlist

class UserVideoListView(ListView):
    '''
    - List the public videos of any user
    - List all the videos of the logged in user
    '''

    model = Video
    template_name = 'channel/index.html'
    context_object_name = 'videos'

    def get_queryset(self):
        '''
        Custom queryset to fetch only public videos
        '''

        username = self.kwargs.get('username')
        if self.request.user.username == username:
            self.user = self.request.user
            return self.model.objects.filter(user=self.request.user).order_by('-created')

        self.user = get_object_or_404(User, username=username)
        return self.model.objects.filter(user=self.user, visibility='PUBLIC').order_by('-created')

    def get_context_data(self, *args, **kwargs):
        context_data = super(
            UserVideoListView, self).get_context_data(*args, **kwargs)
        context_data['channel_user'] = self.user
        return context_data


class PlaylistListView(UserVideoListView):
    model = Playlist
    context_object_name = 'playlists'
    template_name = 'channel/playlist.html'

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        self.user = user
        if self.request.user.id == user.id:
            return Playlist.objects.filter(user=self.request.user)

        return Playlist.objects.filter(user=user, visibility='PUBLIC')

mytube/apps/video/views.py
import datetime

from django.shortcuts import reverse, get_object_or_404, Http404, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Video, Comment, History, VideoRating
from mytube.apps.playlist.models import Playlist


class VideoDetailView(DetailView):
    '''
    Watch video page
    '''

    model = Video
    template_name = 'video/watch.html'

    def get_object(self, queryset=None):
        video_object: Video = super(
            VideoDetailView, self).get_object(queryset=queryset)

        if video_object.visibility == 'PRIVATE' and video_object.user.id != self.request.user.id:
            raise Http404

        if self.request.user.is_authenticated:
            # Increment video view count and reload object
            video_object.increment_view_count()
            video_object.save()
            video_object.refresh_from_db()

            # Create new entry in user history
            try:
                user_last_viewed_video: History = History.objects.get(
                    user=self.request.user, video=video_object)
                user_last_viewed_video.watched_time = datetime.datetime.now()
                user_last_viewed_video.save()
            except:
                import traceback
                traceback.print_exc()
                History(user=self.request.user, video=video_object).save()
        return video_object

    def get_context_data(self, **kwargs):
        context_data = super(VideoDetailView, self).get_context_data(**kwargs)

        playlists = []

        if self.request.user.is_authenticated:
            for playlist in Playlist.objects.filter(user=self.request.user).order_by('deletable'):
                playlists.append({
                    'id': playlist.id,
                    'name': playlist.name,
                    'has_video': playlist.has_video(context_data['video'])
                })

        context_data['playlists'] = playlists
        return context_data


class AddVideoView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account:login')
    model = Video
    template_name = 'video/add.html'
    fields = ['title', 'video_file', 'visibility', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('video:watch', args=(self.object.pk,))


class AddCommentView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('account:login')
    model = Comment
    template_name = 'video/add_comment.html'
    fields = ['text']

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.video = get_object_or_404(Video, id=self.kwargs.get('pk'))
        form.instance.video = self.video
        form.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('video:watch', args=(self.video.pk,))


@login_required(login_url=reverse_lazy('account:login'))
def rate_video(request, pk):
    if request.method == 'POST':
        rating = request.POST.get('rating')

        if rating not in ['LIKE', 'DISLIKE']:
            rating = 'LIKE'

        video: Video = get_object_or_404(
            Video, id=pk, visibility__in=['PUBLIC', 'UNLISTED'])
        video_rating = video.user_rating(request.user, get_rating_object=True)

        if video_rating is not None:
            # If user has already rated the video delete the previously
            # rated item

            if video_rating.rating != rating:
                # Create new rating only if the previously rated value
                # is not being toggled

                VideoRating(user=request.user, video=video,
                            rating=rating).save()

            video_rating.delete()
        else:
            VideoRating(user=request.user, video=video, rating=rating).save()

        return HttpResponseRedirect(reverse('video:watch', kwargs={'pk': video.pk}))

    raise Http404

mytube/apps/video/templates/video/add.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Upload{% endblock %}
{% block content %}
<div class="subtitle">Add new video</div>
<form method="POST" class="column is-half" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'form_template.html' with form=form %}
    <p class="control has-text-right">
        <button class="button is-link" type="submit">Upload</button>
    </p>
</form>


{% endblock %}

mytube/apps/video/templates/video/add_comment.html
{{ form }}

mytube/apps/video/templates/video/list.html
{% extends 'base.html' %}
{% load humanize %}
{% load video_extras %}
{% block content %}
<div class="container is-fluid">
    <div class="subtitle">Recently Uploaded</div>
    <div class="columns is-multiline">
        {% for video in videos %}
        <div class="column is-3">
            <div class="video-list-thumb">
                <a href="{% url 'video:watch' video.id %}">

                    {% if video.preview_thumb %}
                    <img src="{{ video.preview_thumb.url }}" />
                    {% else %}
                    <img src="https://via.placeholder.com/320x180" />
                    {% endif %}
                </a>

                <div class="video-thumb-duration">
                    {% get_duration video.duration %}
                </div>
            </div>
            <div>
                <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                    <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                </a>
                <a href="{% url 'channel:index' video.user.username %}" class="is-size-7">
                    {{video.user.username }}</a>
                <div class="is-size-7 has-text-grey level">
                    <span class="level-left">
                        <span class="level-item">
                            {{ video.created|naturaltime }}
                        </span>
                    </span>
                    <span class="level-right">
                        <span class="level-item">
                            {{ video.views }} views
                        </span>
                    </span>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

mytube/apps/video/templates/video/playlist_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load video_extras %}
{% block title %}{{ playlist.name }}{% endblock %}

{% block content %}
<div class="container is-fluid">
    <div class="subtitle mb-small">{{ playlist.name }}</div>
    <div class="mb-medium is-size-7">
        {% if playlist.visibility == 'PRIVATE' %}
            <span class="p-small has-background-primary has-text-black">Private</span>
        {% endif %}
        {{ playlist.length }} videos.
    </div>
    
    <div class="columns is-multiline">
    {% for entry in entries %}
    {% with video=entry.video %}
            <div class="column is-3">
                <div class="video-list-thumb">
                    <a href="{% url 'video:watch' video.id %}">

                        {% if video.preview_thumb %}
                        <img src="{{ video.preview_thumb.url }}" />
                        {% else %}
                        <img src="https://via.placeholder.com/320x180" />
                        {% endif %}
                    </a>

                    <div class="video-thumb-duration">
                        {% get_duration video.duration %}
                    </div>
                </div>
            </div>
            <div class="column is-3">
                <a href="{% url 'video:watch' video.id %}" class="has-text-white">
                    <h3 class="video-list-title" title="{{ video.title }}">{{ video.title |truncatechars:60 }}</h3>
                </a>
                <a href="{% url 'channel:index' video.user.username %}" class="is-size-7 has-text-link">
                    {{video.user.username }}</a>
                    <div class="is-size-7 has-text-grey">
                        {{ video.views }} views
                    </div>
                    <div class="is-size-7">
                        {{ video.description |truncatechars:100}}
                    </div>
            </div>
            {% endwith %}
            {% endfor %}
        </div>
</div>

{% endblock %}

mytube/apps/video/templates/video/watch.html
{% extends 'skeleton.html' %}
{% load video_extras %}
{% load humanize %}
{% block title %}{{ video.title }}{% endblock %}
{% block body %}
<div class="columns has-background-black is-centered mt-0">
    <div class="column has-text-centered is-paddingless">
        <video controls="" style="height: 80vh; width: 100%" autoplay>
            <source src="{{ video.video_file.url }}" type="video/mp4" />
            Your browser does not support HTML5
        </video>
    </div>
</div>
<section class="section container is-fluid" style="padding-top: 0.5rem;">
    <div class="columns">
        <div class="column is-9">
            <div class="level">
                <div class="level-left">
                    <div class="level-item">
                        <div>
                            <h1 class="subtitle has-text-white mb-small">
                                {{ video.title }}
                            </h1>
                            {{ video.views }} views
                        </div>
                    </div>
                </div>
                <div class="level-right rating-level">
                    <div class="level-item">
                        <div class="rating-container">
                            <form method="POST" action="{% url 'playlist:add' %}">
                                {% csrf_token %}
                                {% user_watch_later_id user as watch_later_playlist %}
                                <input type="hidden" name="playlist_pk" value="{{ watch_later_playlist }}" />
                                <input type="hidden" name="video_pk" value="{{ video.id }}" />
                                {% is_in_playlist video.id watch_later_playlist as in_playlist %}
                                <button title="Watch later" class="button {% if in_playlist %}is-primary{% else %}is-dark{% endif %} is-small">
                                    <i class="fas fa-clock"></i>
                                </button>
                            </form>

                            <form method="POST" action="{% url 'playlist:add' %}">
                                {% csrf_token %}
                                {% user_favourites_id user as favourites_playlist %}
                                <input type="hidden" name="playlist_pk" value="{{ favourites_playlist }}" />
                                <input type="hidden" name="video_pk" value="{{ video.id }}" />
                                {% is_in_playlist video.id favourites_playlist as in_playlist %}
                                <button title="Add to favourites" class="button {% if in_playlist %}is-primary{% else %}is-dark{% endif %} is-small">
                                    <i class="fas fa-heart"></i>
                                </button>
                            </form>
                            {% if user.is_authenticated %}
                            <button title="Save to list" class="button is-dark is-small" id="add-to-playlist-btn">
                                <i class="fas fa-folder-plus"></i>
                                <span class="ml-small">Save</span>
                            </button>
                            {% else %}
                            <a href="{% url 'account:login'%}" title="Save to list" class="button is-dark is-small">
                                <i class="fas fa-folder-plus"></i>
                                <span class="ml-small">Save</span>
                            </a>
                            {% endif %}
                        </div>
                    </div>

                    <div class="level-item">
                        {% with like_count=video.like_count dislike_count=video.dislike_count %}
                        <div class="rating-container">
                            {% user_rating video user as rating %}
                            {{ user_rating }}
                                <form action="{% url 'video:rate_video' video.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="rating" value="LIKE" />
                                    <button type="submit" class="button is-small {% if rating != 'LIKE' %}is-dark{% else %}is-primary{% endif %}">
                                        <i class="{% if rating == 'LIKE' %}fas{% else %}far{% endif %} fa-thumbs-up"></i>
                                        <span class="ml-small">
                                            {% if like_count > 0 %}
                                                {{ like_count }}
                                            {% else %}
                                                Like
                                            {% endif %}
                                        </span>
                                    </button>
                                </form>

                                <form action="{% url 'video:rate_video' video.pk %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="rating" value="DISLIKE" />
                                    <button class="button ml-small is-small {% if rating != 'DISLIKE' %}is-dark{% else %}is-light{% endif %}">
                                        <i class="{% if rating == 'DISLIKE' %}fas{% else %}far{% endif %} fa-thumbs-down"></i>
                                        <span class="ml-small">
                                            {% if dislike_count > 0 %}
                                                {{ dislike_count }}
                                            {% else %}
                                                Dislike
                                            {% endif %}
                                        </span>
                                    </button>
                                </form>

                            <br />
                            {% if like_count != 0 or dislike_count != 0 %}
                            <div class="video-rating-bar mt-small">
                                <div class="video-rating-bar-like" style="width: {{ video.like_percentage }}%"></div>
                            </div>
                            {% endif %}
                        </div>
                        {% endwith %}
                    </div>
                </div>
            </div>
            <hr />
            <article class="media">
                <figure class="media-left">
                    <p class="image is-64x64">
                        <img class="is-rounded" src="https://bulma.io/images/placeholders/128x128.png">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <a href="{% url 'channel:index' video.user.username %}" class="has-text-primary"><strong>Pranav
                                    Sricharan</strong> 
                                    <small class="has-text-link">@{{video.user.username }}</small></a>
                            <br>
                            <small class="has-text-grey">Published on {{ video.created|date:'Y-m-d'}}</small>
                        </p>

                        <div>
                            {% with description=video.description|format_text|safe %}
                            {{ description|linebreaksbr}}
                            {% endwith %}
                        </div>
                    </div>

                </div>

            </article>

            <div class="mt-medium">
                <h3 class="is-size-5 has-font-style-bold">Comments ({{ video.comments.count }})</h3>
                {% if user.is_authenticated %}
                <article class="media mt-small mb-small">
                    <figure class="media-left">
                        <p class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/128x128.png">
                        </p>
                    </figure>
                    <div class="media-content">
                        <form method="POST" action="{% url 'video:add_comment' video.id %}" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="field">
                            <p class="control">
                                <textarea name="text" class="textarea" placeholder="Add a comment..."></textarea>
                            </p>
                            </div>
                            <nav class="level">
                                <div class="level-left"></div>
                                <div class="level-right">
                                    <div class="level-item">
                                        <button type="submit" class="button is-primary">Submit</a>
                                    </div>
                                </div>
                            </nav>
                        </form>
                    </div>
                </article>
                {% else %}
                <div class="has-text-centered mt-medium mb-medium">
                    <h3>Login to write a comment</h3>
                    <a href="{% url 'account:login' %}" class="button is-info">Login</a>
                </div>
                {% endif %}
                {% if video.comments.count > 0 %}
                    {% for comment in video.comments.all %}
                    <article class="media">
                        <figure class="media-left">
                            <p class="image is-64x64">
                            <img src="https://bulma.io/images/placeholders/128x128.png">
                            </p>
                        </figure>
                        <div class="media-content">
                            <div class="content">
                            <p>
                                <strong class="has-text-primary">{{ comment.user.get_name }}</strong> <small class="has-text-link">@{{ comment.user.get_username }}</small> <small>{{ comment.created | naturaltime }}</small>
                                <br>
                                {{ comment.text | linebreaksbr }}
                            </p>
                            </div>
                            
                        </div>
                    </article>
                    {% endfor %}
                {% else %}
                    <center>
                        No comments
                    </center>
                {% endif %}
            </div>
        </div>
        <div class="column is-3">
            <div class="subtitle">
                Related videos
            </div>
        </div>
    </div>
</section>

<div id="playlist-modal" class="modal">
    <div id="playlist-modal-background" class="modal-background"></div>
    <div class="modal-content" style="overflow-x: hidden; max-width: 500px;">
        <div class="box has-background-dark">
            <form class="columns is-multiline has-background-black" action="{% url 'playlist:add' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="video_pk" value="{{ video.id }}" />
                <label class="label column is-12 is-size-7 pb-0 mb-0">Create new playlist</label>
                <div class="column is-6">
                    <input name="name" class="input is-small" type="text" placeholder="New playlist" />
                </div>
                <div class="column">
                    <div class="select is-small">
                        <select name="visibility">
                            <option value="PUBLIC">Public</option>
                            <option value="PRIVATE">Private</option>
                        </select>
                    </div>
                </div>
                <div class="column has-text-right"><button class="button is-small is-primary">Create</button></div>
            </form>
            <div class="p-large columns is-multiline has-background-primary has-text-white">
                {% for playlist in playlists %}
                <div class="column is-8 pt-0 pb-0">{{ playlist.name }}</div>
                <div class="column is-4 has-text-right pt-0 pb-0">
                    <form action="{% url 'playlist:add' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="playlist_pk" value="{{ playlist.id }}" />
                        <input type="hidden" name="video_pk" value="{{ video.id }}" />
                        {% if playlist.has_video %}
                            <button class="button is-text has-text-black is-small">Remove</button>
                        {% else %}
                            <button class="button is-black is-small">Add</button>
                        {% endif %}
                    </form>
                </div>
    
                {% endfor %}
            
            </div>
            
        </div>
    </div>
    <button id="playlist-modal-close" class="modal-close is-large" aria-label="close"></button>
</div>

<script>
    var playlistModal = document.getElementById("playlist-modal");

    document.getElementById("add-to-playlist-btn").addEventListener("click", function(e) {
        playlistModal.classList.add("is-active");
    });

    function _closeModal(e, modal) {
        modal.classList.remove('is-active');
    }

    function closeAddToPlaylist(e) {
        _closeModal(e, playlistModal);
    }

    document.getElementById("playlist-modal-close").addEventListener("click", closeAddToPlaylist);
    document.getElementById("playlist-modal-background").addEventListener("click", closeAddToPlaylist);
</script>
{% endblock %}