mytube/apps/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.login, name='login'),
    path('create', views.register, name='register'),
    path('logout', views.logout, name='logout'),
]

mytube/apps/channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<str:username>', views.UserVideoListView.as_view(), name='index'),
    path('<str:username>/playlists',
         views.PlaylistListView.as_view(), name='playlists')
]

mytube/apps/feed/urls.py
from django.urls import path

from . import views
app_name = 'feed'

urlpatterns = [
    path('', views.MainFeedView.as_view(), name='index'),
    path('history', views.HistoryListView.as_view(), name='history'),
    path('liked', views.LikedVideosListView.as_view(), name='liked'),
    path('most-viewed', views.MostViewedListView.as_view(), name='most-viewed'),
    path('top', views.TopRatedListView.as_view(), name='top'),
]

mytube/apps/video/urls.py
from django.urls import path

from . import views
app_name = 'video'

urlpatterns = [
    path('<pk>', views.VideoDetailView.as_view(), name='watch'),
    path('<pk>/add_comment', views.AddCommentView.as_view(), name='add_comment'),
    path('<pk>/rate', views.rate_video, name='rate_video'),
    path('new', views.AddVideoView.as_view(), name='add'),
]

mytube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mytube.apps.feed.urls', namespace='feed')),
    path('u/', include('mytube.apps.channel.urls', namespace='channel')),
    path('v/', include('mytube.apps.video.urls', namespace='video')),
    path('p/', include('mytube.apps.playlist.urls', namespace='playlist')),
    path('account/', include('mytube.apps.account.urls', namespace='account')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% extends 'skeleton.html' %}

{% block body %}
<div class="columns" style="min-height: calc(100vh - 3.25rem); margin-top: 0;">
    <div class="column is-2 section pl-normal pr-0 has-background-black">
        <aside class="menu">
            <p class="menu-label">
                Explore
            </p>
            <ul class="menu-list">
                <li>
                    <a class="is-active">
                        <span class="icon">
                            <i class="fas fa-home"></i>
                        </span> Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'feed:most-viewed' %}">
                        <span class="icon">
                            <i class="fas fa-eye"></i>
                        </span> Most viewed
                    </a>
                </li>
                <li>
                    <a href="{% url 'feed:top' %}">
                        <span class="icon">
                            <i class="fas fa-star"></i>
                        </span> Popular
                    </a>
                </li>
            </ul>
            <p class="menu-label">
                Manage
            </p>
            <ul class="menu-list">
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'feed:history' %}">
                        <span class="icon">
                            <i class="fas fa-history"></i>
                        </span> History
                    </a>
                </li>
                <li>
                    <a href="{% url 'feed:liked' %}">
                        <span class="icon">
                            <i class="fas fa-thumbs-up"></i>
                        </span> Liked Videos
                    </a>
                </li>
                <li>
                    <a href="{% url 'playlist:watch_later' %}">
                        <span class="icon">
                            <i class="fas fa-clock"></i>
                        </span> Watch later
                    </a>
                </li>
                <li>
                    <a href="{% url 'playlist:favourites' %}">
                        <span class="icon">
                            <i class="fas fa-heart"></i>
                        </span> Favourites
                    </a>
                </li>
                <li>
                    <a href="{% url 'channel:playlists' user.username %}">
                        <span class="icon">
                            <i class="fas fa-folder"></i>
                        </span> Playlists
                    </a>
                </li>
                {% endif %}
            </ul>
            <p class="menu-label">
                Subscriptions
            </p>
            {% if user.is_authenticated %}
            <div class="column is-size-7 has-text-centered">
                No subscriptions yet
            </div>
            {% else %}
            <div class="column is-size-6 has-text-centered">
                <a href="{% url 'account:login' %}">Login</a> to manage subscriptions
            </div>
            {% endif %}

        </aside>
    </div>
    <div class="column is-10 pl-0">
        <section class="section">
            {% block content %}{% endblock %}
        </section>
    </div>
</div>
{% endblock %}

templates/base_no_padding.html
{% extends 'skeleton.html' %}

{% block body %}
<div class="columns" style="min-height: calc(100vh - 3.25rem);">
    <div class="column is-2 section pl-normal pr-0 has-background-black">
        <aside class="menu">
            <p class="menu-label">
                Explore
            </p>
            <ul class="menu-list">
                <li>
                    <a class="is-active">
                        <span class="icon">
                            <i class="fas fa-home"></i>
                        </span> Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'feed:most-viewed' %}">
                        <span class="icon">
                            <i class="fas fa-eye"></i>
                        </span> Most viewed
                    </a>
                </li>
                <li>
                    <a href="{% url 'feed:top' %}">
                        <span class="icon">
                            <i class="fas fa-star"></i>
                        </span> Popular
                    </a>
                </li>
            </ul>
            <p class="menu-label">
                Manage
            </p>
            <ul class="menu-list">
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'feed:history' %}">
                        <span class="icon">
                            <i class="fas fa-history"></i>
                        </span> History
                    </a>
                </li>
                <li>
                    <a href="{% url 'feed:liked' %}">
                        <span class="icon">
                            <i class="fas fa-thumbs-up"></i>
                        </span> Liked Videos
                    </a>
                </li>
                <li>
                    <a href="{% url 'playlist:watch_later' %}">
                        <span class="icon">
                            <i class="fas fa-clock"></i>
                        </span> Watch later
                    </a>
                </li>
                <li>
                    <a href="{% url 'playlist:favourites' %}">
                        <span class="icon">
                            <i class="fas fa-heart"></i>
                        </span> Favourites
                    </a>
                </li>
                <li>
                    <a href="{% url 'channel:playlists' user.username %}">
                        <span class="icon">
                            <i class="fas fa-folder"></i>
                        </span> Playlists
                    </a>
                </li>
                {% endif %}
            </ul>
            <p class="menu-label">
                Subscriptions
            </p>
            {% if user.is_authenticated %}
            <div class="column is-size-7 has-text-centered">
                No subscriptions yet
            </div>
            {% else %}
            <div class="column is-size-6 has-text-centered">
                <a href="{% url 'account:login' %}">Login</a> to manage subscriptions
            </div>
            {% endif %}

        </aside>
    </div>
    <div class="column is-10 pl-0">
        {% block content %}{% endblock %}
    </div>
</div>
{% endblock %}

templates/base_no_sidebar.html
{% extends 'skeleton.html' %}

{% block body %}
<div class="container is-fluid pt-large">
    {% block content %}{% endblock %}
</div>

{% endblock %}

templates/form_template.html
{% load widget_tweaks %}

{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% if form.non_field_errors %}
<div class="box is-size-7" style="margin-bottom: 1rem;">
    <span class="has-text-weight-semibold">The following errors were found:</span>
    <ul>
        {% for error in form.non_field_errors %}
        <li class="has-text-danger">{{ error }}</li>

        {% endfor %}
    </ul>
</div>
{% endif %}
{% for field in form.visible_fields %}
<div class="field">
    <label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="control">
        {% if field.field.widget.input_type == "select" %}
        <div class="select is-fullwidth">
            {{ field}}
        </div>
        {% elif field.field.widget.input_type == "file" %}
        <div class="file has-name is-fullwidth">
            <label class="file-label">
                <input id="{{ field.id_for_label }}" {% if field.field.required %}required{% endif %} name="{{ field.name }}"
                    class="file-input {% if field.errors %}is-invalid{% endif %}" type="{{ field.field.widget.input_type }}"
                    onchange="if (this.files.length > 0) document.getElementById('{{ field.id_for_label }}-name').innerHTML = this.files[0].name;">
                <span class="file-cta">
                    <span class="file-icon">
                        <i class="fas fa-upload"></i>
                    </span>
                    <span class="file-label">
                        Choose a file
                    </span>
                </span>
                <span class="file-name" id="{{ field.id_for_label }}-name">
                    No file chosen
                </span>
            </label>
        </div>

        {% elif field.field.widget.input_type == "text" or field.field.widget.input_type == "password"%}
        {{ field|add_class:'input' }}
        {% else %}
        {{ field|add_class:'textarea' }}
        {% endif %}
    </div>
    {% for error in field.errors %}
    <p class="help is-danger">{{ error }}</span>
        {% endfor %}
</div>
{% endfor %}

templates/skeleton.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Home{% endblock %} - MyTube</title>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
</head>

<body>
    <div id="nav" class="navbar is-primary is-fixed-top">
        <div class="navbar-brand">
            <a href="/" class="navbar-item">
                <span class="logo is-size-7">
                    <i class="fas fa-play"></i>
                </span>
                <span class="subtitle has-text-black ml-normal">MyTube</span>
            </a>

        </div>
        <div class="navbar-menu">
            <div class="navbar-start">

                <!-- <a class=" navbar-item" href="/">Recent</a>
                <a class="navbar-item" href="/">Popular</a> -->
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field has-addons">
                        <div class="control is-expanded">
                            <input class="input" type="text" placeholder="Search">
                        </div>
                        <div class="control">
                            <button class="button is-black">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
                {% if user.is_authenticated %}
                <a href="{% url 'video:add' %}" class="navbar-item">
                    <span class="icon is-small" style="margin-right: 0.5rem"><i class="fas fa-upload"></i></span>
                    Upload
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a href="#" class="navbar-link">
                        <figure class="image is-32x32" style="margin-right: 0.5rem;">
                            <img class="is-rounded" src="https://via.placeholder.com/32" style="max-height: none;">
                        </figure>
                    </a>
                    <div class="navbar-dropdown is-right has-background-primary">
                        <div class="navbar-item">
                            <div class="columns is-multiline">
                                <div class="column is-12">
                                    <figure class="image is-128x128" style="margin: auto;">
                                        <img class="is-rounded" src="https://via.placeholder.com/128" style="max-height: none;">
                                    </figure>
                                </div>
                                <div class="column is-12 has-text-centered">
                                    <div class="subtitle is-marginless has-text-white">Pranav Sricharan</div>
                                    <span class="has-text-black">{{ user.videos.count }} videos</span>
                                </div>
                            </div>
                        </div>
                        <hr class="navbar-divider" />
                        <a href="{% url 'channel:index' user.username %}" class="navbar-item">
                            Channel
                        </a>
                        <a href="{% url 'feed:history' %}" class="navbar-item">
                            History
                        </a>
                        <a class="navbar-item">
                            Settings
                        </a>
                        <hr class="navbar-divider" />
                        <a href="{% url 'account:logout' %}" class="navbar-item">
                            Logout
                        </a>
                    </div>
                </div>

                {% else %}
                <div class="navbar-item">
                    <div class="buttons">
                        <a href="{% url 'account:login' %}" class="button is-black">Login</a>
                        <a href="{% url 'account:register' %}" class="button is-white is-outlined">Register</a>
                    </div>
                </div>

                {% endif %}
            </div>

        </div>
        <!-- <router-link to="/">Home</router-link> |
                <router-link to="/about">About</router-link> -->
    </div>

    {% block body %}{% endblock %}

</body>

</html>